# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_adduser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adduser(object):
    def setupUi(self, Ui_adduser):
        Ui_adduser.setObjectName("Ui_adduser")
        Ui_adduser.resize(529, 258)
        self.userlineEdit = QtWidgets.QLineEdit(Ui_adduser)
        self.userlineEdit.setGeometry(QtCore.QRect(160, 40, 311, 31))
        self.userlineEdit.setObjectName("userlineEdit")
        self.label = QtWidgets.QLabel(Ui_adduser)
        self.label.setGeometry(QtCore.QRect(60, 30, 101, 51))
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Ui_adduser)
        self.pushButton.setGeometry(QtCore.QRect(100, 190, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Ui_adduser)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 190, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Ui_adduser)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 111, 51))
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Ui_adduser)
        self.comboBox.setGeometry(QtCore.QRect(160, 110, 311, 31))
        self.comboBox.setMaxVisibleItems(16)
        self.comboBox.setIconSize(QtCore.QSize(16, 16))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_sub = QtWidgets.QPushButton(Ui_adduser)
        self.pushButton_sub.setGeometry(QtCore.QRect(360, 190, 91, 41))
        self.pushButton_sub.setObjectName("pushButton_sub")

        self.retranslateUi(Ui_adduser)
        QtCore.QMetaObject.connectSlotsByName(Ui_adduser)

    def retranslateUi(self, Ui_adduser):
        _translate = QtCore.QCoreApplication.translate
        Ui_adduser.setWindowTitle(_translate("Ui_adduser", "用户增加"))
        self.label.setText(_translate("Ui_adduser", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">用户ID：</span></p></body></html>"))
        self.pushButton.setText(_translate("Ui_adduser", "确定添加"))
        self.pushButton_2.setText(_translate("Ui_adduser", "取消"))
        self.label_2.setText(_translate("Ui_adduser", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">权限等级：</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Ui_adduser", "操作员"))
        self.comboBox.setItemText(1, _translate("Ui_adduser", "工程师"))
        self.comboBox.setItemText(2, _translate("Ui_adduser", "管理员"))
        self.pushButton_sub.setText(_translate("Ui_adduser", "删除用户"))
