# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gluemonitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_glue_monitor(object):
    def setupUi(self, glue_monitor):
        glue_monitor.setObjectName("glue_monitor")
        glue_monitor.resize(962, 874)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(glue_monitor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(glue_monitor)
        self.widget_2.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_7 = QtWidgets.QWidget(glue_monitor)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_6 = QtWidgets.QWidget(self.widget_7)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_6)
        self.widget_3.setStyleSheet("background-color: rgb(9, 9, 9);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.widget_6)
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout.addWidget(self.widget_5)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_4 = QtWidgets.QWidget(self.widget_7)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.widget_2.raise_()
        self.verticalLayout.addWidget(self.widget_4)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.widget = QtWidgets.QWidget(glue_monitor)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)

        self.retranslateUi(glue_monitor)
        QtCore.QMetaObject.connectSlotsByName(glue_monitor)

    def retranslateUi(self, glue_monitor):
        _translate = QtCore.QCoreApplication.translate
        glue_monitor.setWindowTitle(_translate("glue_monitor", "实时界面"))
