# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_logindialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(885, 565)
        Dialog.setMinimumSize(QtCore.QSize(885, 565))
        Dialog.setMaximumSize(QtCore.QSize(885, 565))
        Dialog.setStyleSheet("QDialog#Dialog\n"
"{\n"
"border-image: url(res/CATL.png); }")
        self.widget_4 = QtWidgets.QWidget(Dialog)
        self.widget_4.setGeometry(QtCore.QRect(250, 130, 311, 111))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setStyleSheet("font: 14pt \"Arial Unicode MS\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setMinimumSize(QtCore.QSize(87, 0))
        self.label_3.setStyleSheet("font: 14pt \"Arial Unicode MS\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.ptb_key = QtWidgets.QPushButton(self.widget_3)
        self.ptb_key.setMinimumSize(QtCore.QSize(35, 31))
        self.ptb_key.setSizeIncrement(QtCore.QSize(0, 0))
        self.ptb_key.setStyleSheet("QPushButton#ptb_key\n"
"{ border-image: url(res/key.png); }  \n"
"QPushButton:hover#ptb_key\n"
"{ border-image: url(res/key_hover.png); }  \n"
"\n"
"\n"
"")
        self.ptb_key.setText("")
        self.ptb_key.setObjectName("ptb_key")
        self.horizontalLayout_3.addWidget(self.ptb_key)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(Dialog)
        self.widget_5.setGeometry(QtCore.QRect(290, 480, 201, 61))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbt_ensure = QtWidgets.QPushButton(self.widget_5)
        self.pbt_ensure.setMinimumSize(QtCore.QSize(0, 30))
        self.pbt_ensure.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"font: 75 10pt \"Agency FB\";")
        self.pbt_ensure.setObjectName("pbt_ensure")
        self.horizontalLayout_4.addWidget(self.pbt_ensure)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "用户名:"))
        self.label_3.setText(_translate("Dialog", "密码： "))
        self.pbt_ensure.setText(_translate("Dialog", "确认"))
