# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainstation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainStation(object):
    def setupUi(self, MainStation):
        MainStation.setObjectName("MainStation")
        MainStation.resize(1938, 1351)
        MainStation.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainStation.setAutoFillBackground(True)
        MainStation.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainStation)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(MainStation)
        self.frame.setStyleSheet("QWidget#frame\n"
"{    border-image: url(res/4.jpg); \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tipwidget = QtWidgets.QWidget(self.frame)
        self.tipwidget.setStyleSheet("QWidget#tipwidget\n"
"{\n"
"    background-color: rgba(255, 255, 255,30%);\n"
"\n"
"}")
        self.tipwidget.setObjectName("tipwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tipwidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 9, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tipwidget)
        self.label_2.setMinimumSize(QtCore.QSize(232, 88))
        self.label_2.setMaximumSize(QtCore.QSize(232, 88))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.tipwidget)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(416, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.widget_9 = QtWidgets.QWidget(self.tipwidget)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_8 = QtWidgets.QWidget(self.widget_9)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_7 = QtWidgets.QWidget(self.widget_8)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_8.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pbt_changepermission = QtWidgets.QPushButton(self.widget_7)
        self.pbt_changepermission.setMinimumSize(QtCore.QSize(50, 50))
        self.pbt_changepermission.setMaximumSize(QtCore.QSize(50, 50))
        self.pbt_changepermission.setStyleSheet("QPushButton#pbt_changepermission\n"
"{    border-image: url(res/management.png); \n"
"}QPushButton:hover#pbt_changepermission\n"
"{    border-image: url(res/management_hover.png); \n"
"}\n"
"\n"
"")
        self.pbt_changepermission.setText("")
        self.pbt_changepermission.setObjectName("pbt_changepermission")
        self.horizontalLayout_8.addWidget(self.pbt_changepermission)
        self.label_PermissionLevel = QtWidgets.QLabel(self.widget_7)
        self.label_PermissionLevel.setStyleSheet("font: 16pt \"Arial Unicode MS\";\n"
"color: rgb(255, 255, 255);")
        self.label_PermissionLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PermissionLevel.setObjectName("label_PermissionLevel")
        self.horizontalLayout_8.addWidget(self.label_PermissionLevel)
        self.horizontalLayout_9.addWidget(self.widget_7)
        self.widget_6 = QtWidgets.QWidget(self.widget_8)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ptb_help = QtWidgets.QPushButton(self.widget_6)
        self.ptb_help.setMinimumSize(QtCore.QSize(51, 45))
        self.ptb_help.setMaximumSize(QtCore.QSize(51, 45))
        self.ptb_help.setStyleSheet("QPushButton#ptb_help\n"
"{border-image: url(res/help.png);}\n"
"QPushButton:hover#ptb_help\n"
"{border-image: url(res/help_hover.png);}")
        self.ptb_help.setText("")
        self.ptb_help.setObjectName("ptb_help")
        self.horizontalLayout_7.addWidget(self.ptb_help)
        self.pbt_minimize = QtWidgets.QPushButton(self.widget_6)
        self.pbt_minimize.setMinimumSize(QtCore.QSize(49, 46))
        self.pbt_minimize.setMaximumSize(QtCore.QSize(45, 45))
        self.pbt_minimize.setStyleSheet("QPushButton#pbt_minimize\n"
"{    border-image: url(res/minimize.png); \n"
"}QPushButton:hover#pbt_minimize\n"
"{    border-image: url(res/minimize_hover.png); \n"
"}\n"
"\n"
"")
        self.pbt_minimize.setText("")
        self.pbt_minimize.setObjectName("pbt_minimize")
        self.horizontalLayout_7.addWidget(self.pbt_minimize)
        self.pbt_quit = QtWidgets.QPushButton(self.widget_6)
        self.pbt_quit.setMinimumSize(QtCore.QSize(45, 45))
        self.pbt_quit.setMaximumSize(QtCore.QSize(45, 45))
        self.pbt_quit.setStyleSheet("QPushButton#pbt_quit\n"
"{    border-image: url(res/quit.png); \n"
"}QPushButton:hover#pbt_quit\n"
"{    border-image: url(res/quit_hover.png); \n"
"}\n"
"\n"
"\n"
"")
        self.pbt_quit.setText("")
        self.pbt_quit.setObjectName("pbt_quit")
        self.horizontalLayout_7.addWidget(self.pbt_quit)
        self.horizontalLayout_9.addWidget(self.widget_6)
        self.verticalLayout_8.addWidget(self.widget_8)
        spacerItem4 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_3.addWidget(self.widget_9)
        self.widget = QtWidgets.QWidget(self.tipwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3.addWidget(self.widget)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 5)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 5)
        self.label_2.raise_()
        self.widget.raise_()
        self.widget_9.raise_()
        self.verticalLayout_4.addWidget(self.tipwidget)
        self.kexinwidget = QtWidgets.QWidget(self.frame)
        self.kexinwidget.setStyleSheet("QWidget#kexinwidget\n"
"{\n"
"    background-color: rgba(0, 0, 0,0%);\n"
"}")
        self.kexinwidget.setObjectName("kexinwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.kexinwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.funwidget = QtWidgets.QWidget(self.kexinwidget)
        self.funwidget.setMinimumSize(QtCore.QSize(150, 0))
        self.funwidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.funwidget.setStyleSheet("QWidget#funwidget\n"
"{\n"
"    background-color: rgba(255, 255, 255,10%);\n"
"\n"
"}")
        self.funwidget.setObjectName("funwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.funwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fun_showwidget = QtWidgets.QWidget(self.funwidget)
        self.fun_showwidget.setMinimumSize(QtCore.QSize(150, 285))
        self.fun_showwidget.setMaximumSize(QtCore.QSize(150, 285))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.fun_showwidget.setPalette(palette)
        self.fun_showwidget.setStyleSheet("QWidget#funwidget\n"
"{\n"
"    background-color: rgba(0, 0, 0,10%);\n"
"}")
        self.fun_showwidget.setObjectName("fun_showwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fun_showwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbt_realtime = QtWidgets.QPushButton(self.fun_showwidget)
        self.pbt_realtime.setMinimumSize(QtCore.QSize(150, 70))
        self.pbt_realtime.setMaximumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pbt_realtime.setFont(font)
        self.pbt_realtime.setAutoFillBackground(False)
        self.pbt_realtime.setStyleSheet("QPushButton#pbt_realtime\n"
"{\n"
"    background-color: rgba(255, 255, 255,5%);\n"
"    border-color: rgb(255, 255, 255);\n"
"    color: rgb(200, 225, 200);\n"
"}\n"
"QPushButton#pbt_realtime:checked\n"
"{\n"
"    color: rgb(255, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pbt_realtime:hover\n"
"{\n"
"    background-color: rgba(255, 255, 255,15%);\n"
"    border-color: rgb(0, 212, 102);\n"
"}\n"
"\n"
"QPushButton#pbt_realtime:checked:hover\n"
"{\n"
"    background-color: rgba(255, 255, 255,15%);\n"
"    border-color: rgb(0, 212, 102);\n"
"}")
        self.pbt_realtime.setCheckable(True)
        self.pbt_realtime.setObjectName("pbt_realtime")
        self.verticalLayout.addWidget(self.pbt_realtime)
        self.pbt_paramset = QtWidgets.QPushButton(self.fun_showwidget)
        self.pbt_paramset.setMinimumSize(QtCore.QSize(150, 70))
        self.pbt_paramset.setMaximumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pbt_paramset.setFont(font)
        self.pbt_paramset.setStyleSheet("QPushButton#pbt_paramset\n"
"{\n"
"    background-color: rgba(255, 255, 255,5%);\n"
"    border-color: rgb(255, 255, 255);\n"
"    color: rgb(200, 225, 200)\n"
"}\n"
"QPushButton#pbt_paramset:checked\n"
"{\n"
"    \n"
"    \n"
"    color: rgb(255, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pbt_paramset:hover\n"
"{\n"
"    background-color: rgba(255, 255, 255,15%);\n"
"    border-color: rgb(0, 212, 102);\n"
"}\n"
"\n"
"QPushButton#pbt_paramset:checked:hover\n"
"{\n"
"    background-color: rgba(255, 255, 255,15%);\n"
"    border-color: rgb(0, 212, 102);\n"
"}")
        self.pbt_paramset.setCheckable(True)
        self.pbt_paramset.setObjectName("pbt_paramset")
        self.verticalLayout.addWidget(self.pbt_paramset)
        self.pbt_logview = QtWidgets.QPushButton(self.fun_showwidget)
        self.pbt_logview.setMinimumSize(QtCore.QSize(150, 70))
        self.pbt_logview.setMaximumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pbt_logview.setFont(font)
        self.pbt_logview.setStyleSheet("QPushButton#pbt_logview\n"
"{\n"
"    background-color: rgba(255, 255, 255,5%);\n"
"    border-color: rgb(255, 255, 255);\n"
"    color: rgb(200, 225, 200)\n"
"}\n"
"QPushButton#pbt_logview:checked\n"
"{\n"
"    color: rgb(255, 255, 127);\n"
"}\n"
"\n"
"QPushButton#pbt_logview:hover\n"
"{\n"
"    background-color: rgba(255, 255, 255,15%);\n"
"    border-color: rgb(0, 212, 102);\n"
"}\n"
"\n"
"QPushButton#pbt_logview:checked:hover\n"
"{\n"
"    background-color: rgba(255, 255, 255,15%);\n"
"    border-color: rgb(0, 212, 102);\n"
"}")
        self.pbt_logview.setCheckable(True)
        self.pbt_logview.setObjectName("pbt_logview")
        self.verticalLayout.addWidget(self.pbt_logview)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.fun_showwidget)
        self.widget_3 = QtWidgets.QWidget(self.funwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(12, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.widget_11 = QtWidgets.QWidget(self.widget_3)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.widget_2 = QtWidgets.QWidget(self.widget_11)
        self.widget_2.setMinimumSize(QtCore.QSize(72, 95))
        self.widget_2.setMaximumSize(QtCore.QSize(72, 95))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolbtn_onlinerun = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbtn_onlinerun.sizePolicy().hasHeightForWidth())
        self.toolbtn_onlinerun.setSizePolicy(sizePolicy)
        self.toolbtn_onlinerun.setMinimumSize(QtCore.QSize(70, 70))
        self.toolbtn_onlinerun.setMaximumSize(QtCore.QSize(70, 70))
        self.toolbtn_onlinerun.setStyleSheet("QPushButton#toolbtn_onlinerun\n"
"{ border-image: url(res/start1.png); }  \n"
"QPushButton:hover#toolbtn_onlinerun\n"
"{ border-image: url(res/start11.png); \n"
"} \n"
"QPushButton:checked#toolbtn_onlinerun\n"
" { border-image: url(res/stop.png); } ")
        self.toolbtn_onlinerun.setText("")
        self.toolbtn_onlinerun.setCheckable(True)
        self.toolbtn_onlinerun.setChecked(False)
        self.toolbtn_onlinerun.setObjectName("toolbtn_onlinerun")
        self.verticalLayout_5.addWidget(self.toolbtn_onlinerun)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(243, 255, 107);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.verticalLayout_5.setStretch(0, 5)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_11.addWidget(self.widget_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.widget_4 = QtWidgets.QWidget(self.widget_11)
        self.widget_4.setMinimumSize(QtCore.QSize(72, 95))
        self.widget_4.setMaximumSize(QtCore.QSize(72, 95))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolbtn_offlinerun = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbtn_offlinerun.sizePolicy().hasHeightForWidth())
        self.toolbtn_offlinerun.setSizePolicy(sizePolicy)
        self.toolbtn_offlinerun.setMinimumSize(QtCore.QSize(70, 70))
        self.toolbtn_offlinerun.setMaximumSize(QtCore.QSize(70, 70))
        self.toolbtn_offlinerun.setStyleSheet("QPushButton#toolbtn_offlinerun\n"
"{ border-image: url(res/simulate.png); }  \n"
"QPushButton:hover#toolbtn_offlinerun\n"
"{ border-image: url(res/simulated.png); \n"
"} \n"
"QPushButton:checked#toolbtn_offlinerun\n"
" { border-image: url(res/stop.png); } ")
        self.toolbtn_offlinerun.setText("")
        self.toolbtn_offlinerun.setCheckable(True)
        self.toolbtn_offlinerun.setObjectName("toolbtn_offlinerun")
        self.verticalLayout_6.addWidget(self.toolbtn_offlinerun)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(243, 255, 107);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.verticalLayout_11.addWidget(self.widget_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.widget_5 = QtWidgets.QWidget(self.widget_11)
        self.widget_5.setMinimumSize(QtCore.QSize(72, 95))
        self.widget_5.setMaximumSize(QtCore.QSize(72, 95))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.toolbtn_savebadimage = QtWidgets.QPushButton(self.widget_5)
        self.toolbtn_savebadimage.setMinimumSize(QtCore.QSize(70, 70))
        self.toolbtn_savebadimage.setMaximumSize(QtCore.QSize(70, 70))
        self.toolbtn_savebadimage.setStyleSheet("QPushButton#toolbtn_savebadimage\n"
"{ border-image: url(res/save.png); }  \n"
"QPushButton:hover#toolbtn_savebadimage\n"
"{ border-image: url(res/saved.png); \n"
"\n"
"} ")
        self.toolbtn_savebadimage.setText("")
        self.toolbtn_savebadimage.setIconSize(QtCore.QSize(14, 14))
        self.toolbtn_savebadimage.setCheckable(True)
        self.toolbtn_savebadimage.setObjectName("toolbtn_savebadimage")
        self.verticalLayout_9.addWidget(self.toolbtn_savebadimage)
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(243, 255, 107);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.verticalLayout_11.addWidget(self.widget_5)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.widget_10 = QtWidgets.QWidget(self.widget_11)
        self.widget_10.setMinimumSize(QtCore.QSize(72, 95))
        self.widget_10.setMaximumSize(QtCore.QSize(72, 95))
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.toolbtn_advancedfun = QtWidgets.QPushButton(self.widget_10)
        self.toolbtn_advancedfun.setMinimumSize(QtCore.QSize(70, 70))
        self.toolbtn_advancedfun.setMaximumSize(QtCore.QSize(70, 70))
        self.toolbtn_advancedfun.setStyleSheet("QPushButton#toolbtn_advancedfun\n"
"{ border-image: url(res/advance.png); }  \n"
"QPushButton:hover#toolbtn_advancedfun\n"
"{ border-image: url(res/advanced.png); \n"
"\n"
"} \n"
"")
        self.toolbtn_advancedfun.setText("")
        self.toolbtn_advancedfun.setCheckable(True)
        self.toolbtn_advancedfun.setObjectName("toolbtn_advancedfun")
        self.verticalLayout_10.addWidget(self.toolbtn_advancedfun)
        self.label_6 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(243, 255, 107);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.verticalLayout_11.addWidget(self.widget_10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 216, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(8, 2)
        self.horizontalLayout_4.addWidget(self.widget_11)
        spacerItem12 = QtWidgets.QSpacerItem(13, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 10)
        self.horizontalLayout_2.addWidget(self.funwidget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.kexinwidget)
        self.stackedWidget.setStyleSheet("QStackedWidget#stackedWidget\n"
"{\n"
"    background-color: rgba(0, 0, 0, 10%);\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_4.addWidget(self.kexinwidget)
        self.labelwidget = QtWidgets.QWidget(self.frame)
        self.labelwidget.setMinimumSize(QtCore.QSize(0, 41))
        self.labelwidget.setMaximumSize(QtCore.QSize(16777215, 41))
        self.labelwidget.setStyleSheet("QWidget#labelwidget\n"
"{\n"
"    background-color: rgba(0, 0, 0, 1%);\n"
"}")
        self.labelwidget.setObjectName("labelwidget")
        self.verticalLayout_4.addWidget(self.labelwidget)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 17)
        self.verticalLayout_4.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(MainStation)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainStation)

    def retranslateUi(self, MainStation):
        _translate = QtCore.QCoreApplication.translate
        MainStation.setWindowTitle(_translate("MainStation", "Widget"))
        self.label.setText(_translate("MainStation", "在线玻璃检测"))
        self.label_PermissionLevel.setText(_translate("MainStation", "操作员"))
        self.ptb_help.setToolTip(_translate("MainStation", "帮助"))
        self.pbt_quit.setToolTip(_translate("MainStation", "退出系统"))
        self.pbt_realtime.setText(_translate("MainStation", "实时显示"))
        self.pbt_paramset.setText(_translate("MainStation", "参数设置"))
        self.pbt_logview.setText(_translate("MainStation", "日志显示"))
        self.toolbtn_onlinerun.setToolTip(_translate("MainStation", "开始检测"))
        self.label_3.setText(_translate("MainStation", "开始检测"))
        self.toolbtn_offlinerun.setToolTip(_translate("MainStation", "模拟检测"))
        self.label_4.setText(_translate("MainStation", "模拟检测"))
        self.toolbtn_savebadimage.setToolTip(_translate("MainStation", "保存坏图"))
        self.label_5.setText(_translate("MainStation", "保存图片"))
        self.toolbtn_advancedfun.setToolTip(_translate("MainStation", "控制子站"))
        self.label_6.setText(_translate("MainStation", "高级功能"))
